// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCImeW4ym_uPklC1Cmb9gfmjFN0U99jbK0',
    appId: '1:105860403995:web:9f80c8d934cd47d2a479be',
    messagingSenderId: '105860403995',
    projectId: 'fitflow-f5158',
    authDomain: 'fitflow-f5158.firebaseapp.com',
    storageBucket: 'fitflow-f5158.firebasestorage.app',
    measurementId: 'G-SGDHKNVH5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2ziHdutLKvbhLKbrqNXv47PAZgcIni9o',
    appId: '1:105860403995:android:f5e42ce9ed1616dca479be',
    messagingSenderId: '105860403995',
    projectId: 'fitflow-f5158',
    storageBucket: 'fitflow-f5158.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuQ8HYuVNDOvS9YqhY--AaGfV6CJ8tvSM',
    appId: '1:105860403995:ios:d09377fd263f0177a479be',
    messagingSenderId: '105860403995',
    projectId: 'fitflow-f5158',
    storageBucket: 'fitflow-f5158.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow.dev.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuQ8HYuVNDOvS9YqhY--AaGfV6CJ8tvSM',
    appId: '1:105860403995:ios:75e7554e3dbc0778a479be',
    messagingSenderId: '105860403995',
    projectId: 'fitflow-f5158',
    storageBucket: 'fitflow-f5158.firebasestorage.app',
    iosBundleId: 'com.example.fitFlow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCImeW4ym_uPklC1Cmb9gfmjFN0U99jbK0',
    appId: '1:105860403995:web:cafd68134c953765a479be',
    messagingSenderId: '105860403995',
    projectId: 'fitflow-f5158',
    authDomain: 'fitflow-f5158.firebaseapp.com',
    storageBucket: 'fitflow-f5158.firebasestorage.app',
    measurementId: 'G-JB2C5H94P2',
  );
}
